export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const NOMINATION_LIST_REQUEST = "NOMINATION_LIST_REQUEST";
export const NOMINATION_LIST_SUCCESS = "NOMINATION_LIST_SUCCESS";
export const NOMINATION_LIST_FAIL = "NOMINATION_LIST_FAIL";
export const NOMINATION_LIST_RESET = "NOMINATION_LIST_RESET";

export const NOMINATION_DETAILS_REQUEST = "NOMINATION_DETAILS_REQUEST";
export const NOMINATION_DETAILS_SUCCESS = "NOMINATION_DETAILS_SUCCESS";
export const NOMINATION_DETAILS_FAIL = "NOMINATION_DETAILS_FAIL";


