export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";



export const NOMINATION_LIST_REQUEST = "NOMINATION_LIST_REQUEST";
export const NOMINATION_LIST_SUCCESS = "NOMINATION_LIST_SUCCESS";
export const NOMINATION_LIST_FAIL = "NOMINATION_LIST_FAIL";
export const NOMINATION_LIST_RESET = "NOMINATION_LIST_RESET";


