export const USER_VIEW_NOMINATION_LIST_REQUEST = "USER_VIEW_NOMINATION_LIST_REQUEST";
export const USER_VIEW_NOMINATION_LIST_SUCCESS = "USER_VIEW_NOMINATION_LIST_SUCCESS";
export const USER_VIEW_NOMINATION_LIST_FAIL = "USER_VIEW_NOMINATION_LIST_FAIL";
export const USER_VIEW_NOMINATION_LIST_RESET = "USER_VIEW_NOMINATION_LIST_RESET";

export const USER_VIEW_NOMINATION_DETAILS_REQUEST = "USER_VIEW_NOMINATION_DETAILS_REQUEST";
export const USER_VIEW_NOMINATION_DETAILS_SUCCESS = "USER_VIEW_NOMINATION_DETAILS_SUCCESS";
export const USER_VIEW_NOMINATION_DETAILS_FAIL = "USER_VIEW_NOMINATION_DETAILS_FAIL";